language: crystal
script: make spec

os:
  - linux
crystal:
  - latest


jobs:
  include:
    - stage: test
    - if: branch = ci/release-artifacts
      os: osx
    - stage: publish release artifacts
      script: echo "publishing the stuff"

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
